#!/usr/bin/env bash
# Solve every turn-rooted input (turn + river) generated by gen-turn-inputs.mjs.
set -e
INSTALL="/Users/danwilloughby/Documents/Code Projects/TexasSolver/install"
cd "$INSTALL"
for IN in turn_*.txt; do
  OUT="${IN%.txt}_result.json"
  [ -f "$OUT" ] && { echo "skip $IN (done)"; continue; }
  echo "=== solving $IN ==="
  ./console_solver -i "$IN" > "${IN%.txt}.log" 2>&1
  echo "=== done $IN ($(du -h "$OUT" 2>/dev/null | cut -f1)) ==="
done
echo "ALL TURNS DONE"
